/*
              _                             _               _     __   __
         /\  | |                           | |             (_)    \ \ / /
        /  \ | |_ _ __ ___   ___  ___ _ __ | |__   ___ _ __ _  ___ \ V / 
       / /\ \| __| '_ ` _ \ / _ \/ __| '_ \| '_ \ / _ \ '__| |/ __| > <  
      / ____ \ |_| | | | | | (_) \__ \ |_) | | | |  __/ |  | | (__ / . \ 
     /_/    \_\__|_| |_| |_|\___/|___/ .__/|_| |_|\___|_|  |_|\___/_/ \_\
                                     | |                            
                                     |_|                                                                                                                

    Created with ♥ by the AtmosphericX Team (KiyoWx, StarflightWx, & CJ Ziegler)
    Discord: https://atmosphericx-discord.scriptkitty.cafe
    Ko-Fi: https://ko-fi.com/k3yomi
    Documentation: http://localhost/documentation | https://atmosphericx.scriptkitty.cafe/documentation

    Internal Package: @atmosx/event-product-parser

*/

export const EnumTags = {
    SEVERE_WEATHER: [
        { match: /A Large And Extremely Dangerous Tornado/i, tag: "Large and Dangerous Tornado" },
        { match: /This Is A Particularly Dangerous Situation/i, tag: "Particularly Dangerous Situation" },
        { match: /Weather Spotters Confirmed Tornado/i, tag: "Weather Spotters Confirmed Tornado" },
        { match: /Law Enforcement Confirmed Tornado/i, tag: "Law Enforcement Confirmed Tornado" },
        { match: /Radar Confirmed/i, tag: "Radar Confirmed" },
        { match: /Radar Indicated Rotation/i, tag: "Radar Indicated Rotation" },
        { match: /Radar Indicated(?! Rotation)/i, tag: "Radar Indicated" },
        { match: /A Tornado Is On The Ground/i, tag: "Tornado On The Ground" },
        { match: /Tornado Was Reported Briefly On The Ground/i, tag: "Tornado Briefly On Ground" },
        { match: /Weather Spotters Reported Funnel Cloud/i, tag: "Confirmed Funnel Cloud" },
        { match: /Spotters Indicate That A Funnel Cloud Continues With This Storm/i, tag: "Funnel Cloud Continues" },
        { match: /A Severe Thunderstorm Capable Of Producing A Tornado/i, tag: "Tornado Possible" },
        { match: /A Tornado May Develop At Any Time/i, tag: "Tornado May Develop" },
        { match: /A Tornado Watch Remains In Effect/i, tag: "Active Tornado Watch" },
        { match: /Complete Destruction Is Possible/i, tag: "Extremely Damaging Tornado" },
        { match: /Potentially Deadly Tornado/i, tag: "Deadly Tornado" },
        { match: /Life-Threatening Situation/i, tag: "Life Threatening Situation" },
        { match: /Capable Of Producing A Landspout/i, tag: "Landspout Possible" },
        { match: /Public Confirmed Tornado/i, tag: "Public Confirmed Tornado" },
        { match: /Expect Wind Damage/i, tag: "Wind Damage" },
        { match: /Destructive Winds/i, tag: "Destructive Winds" },
        { match: /Wind Damage With This Storm Will Occur/i, tag: "Immediate Wind Damage Threat" },
        { match: /Widespread Wind Damage/i, tag: "Widespread Wind Damage" },
        { match: /Significant Wind Damage/i, tag: "Significant Wind Damage" },
        { match: /Tornado Like Wind Speeds/i, tag: "Tornado-Like Wind Speeds" },
        { match: /Winds Will Strengthen/i, tag: "Strengthening Winds" },
        { match: /Gusty Winds/i, tag: "Gusty Winds" },
        { match: /Could Knock Down Tree Limbs/i, tag: "Tree Damage Possible" },
        { match: /Blow Around Unsecured Objects/i, tag: "Loose Object Damage Possible" },
        { match: /Unsecured lightweight objects blown about/i, tag: "Loose Objects May Blow Around" },
        { match: /Many large tree limbs broken off/i, tag: "Tree Limb Damage Possible" },
        { match: /Some fences and roadway signs blown over/i, tag: "Fence and Sign Damage Possible" },
        { match: /Hazardous driving conditions on bridges/i, tag: "Hazardous Bridge Travel" },
        { match: /Scattered power and communications outages/i, tag: "Power Outages Possible" },
        { match: /Hail Damage To Vehicles Is Expected/i, tag: "Vehicle Damaging Hail" },
        { match: /Extremely Large Hail/i, tag: "Extremely Large Hail" },
        { match: /(?<!Extremely )Large Hail/i, tag: "Large Hail" },
        { match: /Tennis Ball Size Hail/i, tag: "Tennis Ball Size Hail" },
        { match: /Baseball Size Hail/i, tag: "Baseball Size Hail" },
        { match: /Golf Ball Size Hail/i, tag: "Golf Ball Size Hail" },
        { match: /Quarter Size Hail/i, tag: "Quarter Size Hail" },
        { match: /Ping Pong Ball Size Hail/i, tag: "Ping Pong Ball Size Hail" },
        { match: /Nickel Size Hail/i, tag: "Nickel Size Hail" },
        { match: /Hail Driven By Severe Winds/i, tag: "Wind Driven Hail" },
        { match: /Prepare Immediately For Large Hail/i, tag: "Large Hail" },
        { match: /Half Inch Hail/i, tag: "Half Inch Hail" },
        { match: /Frequent Lightning/i, tag: "Frequent Lightning" },
        { match: /Deadly Cloud To Ground Lightning/i, tag: "Deadly Cloud To Ground Lightning" },
        { match: /Continuous Cloud To Ground Lightning/i, tag: "Continuous Cloud To Ground Lightning" },
        { match: /Frequent Cloud To Ground Lightning/i, tag: "Frequent Cloud To Ground Lightning" },
        { match: /Lightning Can Strike \d+ Miles Away/i, tag: "Lightning Safety Threat" },
        { match: /Showers and thunderstorms with gusty winds may still occur/i, tag: "Gusty Thunderstorms Possible" },
        
    ],

    FLOOD: [
        { match: /Flash Flooding Caused By Thunderstorms/i, tag: "Thunderstorm Flash Flooding" },
        { match: /Flash Flooding Caused By Heavy Rain/i, tag: "Heavy Rain Flash Flooding" },
        { match: /Torrential Rainfall/i, tag: "Torrential Rainfall" },
        { match: /May Lead To Flash Flooding/i, tag: "Flash Flooding Possible" },
        { match: /Minor Flooding Is Occurring/i, tag: "Minor Flooding Occurring" },
        { match: /Localized Flooding/i, tag: "Localized Flooding Possible" },
        { match: /Do Not Drive Your Vehicle Through Flooded Roadways/i, tag: "Flooded Roadways" },
        { match: /No storm surge inundation forecast/i, tag: "No Storm Surge Inundation" },
        { match: /Localized storm surge possible/i, tag: "Localized Storm Surge Possible" },
        { match: /Peak Storm Surge Inundation/i, tag: "Storm Surge Inundation Risk" },
        { match: /Potential for storm surge flooding/i, tag: "Storm Surge Flooding Possible" },
        { match: /Small streams, creeks, and ditches may become swollen/i, tag: "Small Stream Flooding Risk" },
        { match: /Rivers and tributaries may quickly rise/i, tag: "Rapid River Rise Possible" },
        { match: /Flood waters can enter a few structures/i, tag: "Flood Damage Possible" },
        { match: /Rapid ponding of water occurs/i, tag: "Water Ponding Possible" },
        { match: /Brief road and bridge closures/i, tag: "Road Closures Possible" },
        
    ],

    WINTER_WEATHER: [
        { match: /Frostbite And Hypothermia Are Likely/i, tag: "Frostbite and Hypothermia Likely" },
        { match: /Very Cold Temperatures Can Lead To Hypothermia/i, tag: "Hypothermia Risk" },
        { match: /Hypothermia If Precautions Are Not Taken/i, tag: "Hypothermia Risk" },
        { match: /Frostbite And Hypothermia Will Occur If Unprotected Skin/i, tag: "Frostbite Risk" },
        { match: /Temperatures Could Cause Ruptured Water Pipes/i, tag: "Ruptured Water Pipes Possible" },
        { match: /Blowing Snow Which Could Reduce Visibility/i, tag: "Reduced Visibility From Blowing Snow" },
        { match: /Lake Effect Snow Expected/i, tag: "Lake Effect Snow" },
        { match: /Slick And Icy Spots On Roads/i, tag: "Icy Roads" },
        { match: /Hazardous Roadways And Black Ice/i, tag: "Black Ice" },
        { match: /Icy Patches May Be More Common On Bridges/i, tag: "Bridge Icing" },
    ],

    COASTAL_MARINE: [
        { match: /Rip Currents Can Sweep Even The Best Swimmer/i, tag: "Dangerous Rip Currents" },
        { match: /Small Craft Could Be Damaged/i, tag: "Small Craft Damage Possible" },
        { match: /No Tsunami Threat/i, tag: "No Tsunami Threat" },
        { match: /Tsunami Threat Exists/i, tag: "Tsunami Threat Exists" },
        { match: /TROPICAL STORM WARNING IN EFFECT/i, tag: "Tropical Storm Warning" },
        { match: /TROPICAL STORM WARNING REMAINS IN EFFECT/i, tag: "Tropical Storm Warning Continues" },
        { match: /Tropical storm[- ]force winds/i, tag: "Tropical Storm Force Winds" },
        { match: /hazardous wind/i, tag: "Hazardous Winds" },
        { match: /hazardous seas/i, tag: "Hazardous Seas" },
        { match: /could capsize or damage vessels/i, tag: "Vessel Damage Risk" },
        { match: /reduce visibility/i, tag: "Reduced Visibility" },
        { match: /Mariners should alter plans/i, tag: "Marine Travel Disruption" },
        { match: /Remain in port/i, tag: "Remain In Port" },
        { match: /seek safe harbor/i, tag: "Seek Safe Harbor" },
        { match: /secure the vessel for severe conditions/i, tag: "Secure Vessel" },
    ],

    SAFETY_INFO: [
        { match: /Seek Shelter Now/i, tag: "Seek Shelter Now" },
        { match: /Seek Shelter Immediately/i, tag: "Seek Shelter Immediately" },
        { match: /Move To An Interior Room/i, tag: "Move To Interior Room" },
        { match: /Move To Safe Shelter Now/i, tag: "Move To Safe Shelter" },
        { match: /Potentially Deadly Storm/i, tag: "Potentially Deadly Storm" },
        { match: /Serious Injury And Significant Property Damage/i, tag: "Serious Damage Possible" },
        { match: /People And Animals Outdoors Will Be Injured/i, tag: "Outdoor Injury Risk" },
        { match: /IMMINENT DANGEROUS WEATHER CONDITIONS/i, tag: "Imminent Dangerous Weather" },
        { match: /Follow the instructions of local officials/i, tag: "Follow Local Officials" },
        { match: /Monitor forecasts/i, tag: "Monitor Forecast Updates" },
        { match: /Complete preparations.*before conditions become unsafe/i, tag: "Complete Preparations Early" },
        { match: /Leave immediately if evacuation orders are given/i, tag: "Evacuate If Ordered" },
        { match: /Heed any flood watches and warnings/i, tag: "Monitor Flood Alerts" },
        { match: /Listen for changes in the forecast/i, tag: "Stay Weather Aware" },
        { match: /Travel Could Be Very Difficult/i, tag: "Difficult Travel Conditions" },
        { match: /Expect Disruptions/i, tag: "Travel Disruptions Expected" },
        { match: /Trained Weather Spotters/i, tag: "Confirmed By Storm Spotters" },
        { match: /Doppler Radar/i, tag: "Confirmed By Radar" },
        { match: /Source\.\.\.Storm Spotters/i, tag: "Confirmed By Storm Spotters" },
        { match: /Source\.\.\.Doppler Radar/i, tag: "Confirmed By Radar" },
        { match: /Source\.\.\.Automated Gauges/i, tag: "Confirmed By Automated Gauges" },
        { match: /Source\.\.\.Radar Confirmed/i, tag: "Confirmed By Radar" },
        { match: /Source\.\.\.Radar Indicated/i, tag: "Radar Indicated" },
        { match: /Source\.\.\.Public/i, tag: "Confirmed By Public" },
        { match: /Source\.\.\.Amateur Radio/i, tag: "Confirmed By Amateur Radio" },
        { match: /Source\.\.\.Emergency Management/i, tag: "Confirmed By Emergency Management" },
        { match: /Source\.\.\.Law Enforcement Reported/i, tag: "Confirmed By Law Enforcement" },
        { match: /Source\.\.\.Broadcast Media/i, tag: "Confirmed By Broadcast Media" },
        { match: /Source\.\.\.Media/i, tag: "Confirmed By Media" },
        { match: /Source\.\.\.Media Reported/i, tag: "Confirmed By Media" },
        { match: /Doppler Radar And Automated Gauges/i, tag: "Confirmed By Radar and Gauges" },
        { match: /Potential Impacts:\s*Limited/i, tag: "Limited Impacts Expected" },
        { match: /Potential Impacts:\s*Little to None/i, tag: "Minimal Impacts Expected" },
        { match: /Slow Down And Allow Extra Time/i, tag: "Allow Extra Travel Time" },
        { match: /Should Exercise Caution/i, tag: "Exercise Caution" },
        { match: /Heat Illnesses/i, tag: "Heat Illness Risk" },
        { match: /\bIntensifying\b/i, tag: "Intensifying Conditions" },
    ],
};